### ISSUE TITLE
Include `nagios_host_context` as a field in nrpe relation databag

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/charm-nrpe#183]
In order to be able to fix [this issue in cos-proxy](https://github.com/canonical/cos-proxy-operator/issues/134) would be necessary to have `nagios_host_context` as a field in [nrpe relation databag](https://github.com/canonical/charm-nrpe/blob/master/hooks/nrpe_helpers.py#L270) so we can use it to discover `juju_application` and `juju_unit`

I'm not familiar with this charm, but as far as I understand the change would be minimal:

```diff
@@ -269,6 +269,7 @@ class MonitorsRelation(helpers.RelationContext):
 
         relation_info = {
             "target-id": self.principal_relation.nagios_hostname(),
+            "nagios_host_contetext": hookenv.config("nagios_host_context"),
             "monitors": self.get_monitors(),
             "private-address": address,
             "ingress-address": address,
```

Do you think this change is possible?

**Comment by simskij** [comment]
`nagios_host_contetext` -> `nagios_host_context` 😅
