### ISSUE TITLE
cis_audit_profile Config Update: 'cis_' Prefix Required for Cron Job but Causes Issues with NRPE Checks

### ISSUE THREAD

**Issue by ashugauttam225** [canonical/charm-nrpe#207]
When updating the cis_audit_profile configuration in the NRPE charm, the use of the "cis_" prefix creates an inconsistency. If we set cis_audit_profile="level2_server", the cron job fails to run, but the NRPE check for CIS audit works correctly. 
Conversely, when we set cis_audit_profile="cis_level2_server", the cron job runs successfully, but the NRPE check produces an error, stating that the profile is an invalid choice. 
This inconsistency requires manual intervention and creates a conflict where the configuration works for one aspect but fails for the other. Ideally, the charm should handle the prefix internally to allow both the cron job and NRPE checks to function correctly without manual adjustment.

**Comment by marcusboden** [comment]
I just had a look at this and realized: This is already fixed in
https://github.com/canonical/charm-nrpe/releases/tag/rev125

However, it didn't land on stable yet, which is why we ran into this issue. Anyway, you can close the issue here.
